apiVersion: apps/v1
kind: Deployment
metadata:
        name: amirali1690-capstone
        labels:
                app: amirali1690-capstone-app
spec:
        replicas: 3
        selector:
                matchlabels:
                        app: amirali1690-capstone-app
        strategy:
                type: RollingUpdate
                rollingUpdate:
                        maxSurge: 1
                        maxUnavailable: 1
        minReadySeconds: 60
        progresDeadlineSeconds: 600

        template:
                metadata:
                        labels:
                                app: amirali1690-capstone-app
                spec:
                        containers:
                                - name: 
                                  image: amirali1690/capstone
                                  ports:
                                          - containerPort: 80
                                  livenessProbe:
                                          failureThreshold: 5
                                          httpGet:
                                                  path: /
                                                  scheme: HTTP
                                                  port: 80
                                          successThreshold: 1
                                          periodSeconds: 30
                                          failureThreshold: 3
                                          timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata: amirali1690-capstone
spec:
        type: LoadBalancer
        selector:
                app: amirali1690-capstone-app
        ports:
                - name: http
                  protocol: TCP
                  port: 80
                  targetPort: 80

