apiVersion: apps/v1
kind: Deployment
metadata:
        name: amirali1690-capstone
        labels:
                app: amirali1690-capstone
spec:
        replicas: 3
        selector:
                matchLabels:
                        app: amirali1690-capstone
        strategy:
                type: RollingUpdate
                rollingUpdate:
                        maxSurge: 1
                        maxUnavailable: 1

        template:
                metadata:
                        labels:
                                app: amirali1690-capstone
                spec:
                        containers:
                                - name: capstone-container
                                  image: amirali1690/capstone
                                  ports:
                                          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
        name: amirali1690-capstone
spec:
        type: LoadBalancer
        ports:
                - name: http
                  protocol: TCP
                  port: 80
                  targetPort: 80
        selector:
                app: amirali1690-capstone

