apiVersion: apps/v1
kind: Deployment
metadata:
  name: amirali1690-capstone
  labels:
    app: amirali1690-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amirali1690-capstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: amirali1690-capstone
    spec:
      containers:
        - name: amirali1690-capstone
          image: amirali1690/capstone
          ports:
          - containerPort: 80
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              scheme: HTTP
              port: 80
            successThreshold: 1
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: amirali1690-capstone
spec:
  type: LoadBalancer
  selector:
    app: amirali1690-capstone
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
